# Generated by Django 5.2.5 on 2025-08-07 03:34

import streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='rtsp_url',
            field=models.CharField(max_length=500, validators=[streaming.models.validate_rtsp_url]),
        ),
    ]
